### PR TITLE
Throw exception when sending transaction fails

### LINKED ISSUE #68: Implement error handling for transaction request
Based on the libra documentation and source code comments the only ok response is a "Valid" code in AdmissionControlStatus. All other cases (VMStatus with all codes and MempoolStatus with all codes) are errors.
- Create a result class for the successful response
- Create exceptions (AdmissionControlException, MempoolException, VirtualMachineException) with status codes, messages and possible status code explanations for error cases. All exception should extend a common exception like LibraTransactionException

### PR DESCRIPTION
**Pull request by ketola**
After a new transaction is sent, the only valid response is AdmissionControl status with code Accepted. All others are some type of errors and are now converted to exceptions depending on the error type.

The vm status is a bit problematic because it does not have an enum for the values like the others. So far I have been only able to find the explanations for the codes from the libra source code.

Fixes #68

### CODE REVIEW

File: jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/result/SubmitTransactionException.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package dev.jlibra.admissioncontrol.transaction.result;
+
+import dev.jlibra.LibraRuntimeException;
+
+public class SubmitTransactionException extends LibraRuntimeException {
```
Comment (hczerpak) [inline jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/result/SubmitTransactionException.java]: I think this should be checked exception because client of SubmitTransactionResult. fromGrpcObject, most likely, would like to handle success and failure. Since there is either success or exception then declaring exception on the method definition would help handling failure. What do you think?

Comment (ketola) [reply jlibra-core/src/main/java/dev/jlibra/admissioncontrol/transaction/result/SubmitTransactionException.java]: I think you're right, the exception needs to be handled always so it makes sense to make it checked
